=== FC-Dijkstra/SiteFormation_DAW/back/XML/old/QCM.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT QCM (meta, question+)>
<!ELEMENT question (valeur, enonce, reponse+)>
<!ELEMENT enonce (#PCDATA)>
<!ELEMENT reponse (type, content)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT meta (cours, difficulte)>
<!ELEMENT cours (#PCDATA)>
<!ELEMENT difficulte (#PCDATA)>
<!ELEMENT valeur (#PCDATA)>

=== FC-Dijkstra/SiteFormation_DAW/back/XML/old/QCM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE QCM SYSTEM "QCM.dtd">
<QCM>
    <meta>
        <cours>DÃ©veloppement WEB</cours>
        <difficulte>Facile</difficulte>
    </meta>
    <question>
        <valeur>1</valeur>
        <enonce>a t'on besoin de faire ces choses ?</enonce>
        <reponse>
            <type>neutral</type>
            <content>non</content>
        </reponse>
        <reponse>
            <type>invalid</type>
            <content>ptet</content>
        </reponse>
        <reponse>
            <type>valid</type>
            <content>oui</content>
        </reponse>
    </question>
    <question>
        <valeur>2</valeur>
        <enonce>LA QUESTION DEEUX ?</enonce>
        <reponse>
            <type>neutral</type>
            <content>non</content>
        </reponse>
        <reponse>
            <type>invalid</type>
            <content> en rouge</content>
        </reponse>
        <reponse>
            <type>valid</type>
            <content> d'accord</content>
        </reponse>
    </question>
</QCM>
