=== FC-Dijkstra/SiteFormation_DAW/back/XML/QCM.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT QCM (meta, question+)>
<!ELEMENT question (valeur, enonce, reponse+)>
<!ELEMENT enonce (#PCDATA)>
<!ELEMENT reponse (#PCDATA)>
<!ELEMENT meta (cours, difficulte)>
<!ELEMENT cours (#PCDATA)>
<!ELEMENT difficulte (#PCDATA)>
<!ELEMENT valeur (#PCDATA)>

=== FC-Dijkstra/SiteFormation_DAW/back/XML/QCM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE QCM SYSTEM "QCM.dtd">
<QCM>
    <meta>
        <cours>DÃ©veloppement WEB</cours>
        <difficulte>Facile</difficulte>
    </meta>
    <question>
        <valeur>1</valeur>
        <enonce>a t'on besoin de faire ces choses ?</enonce>
        <reponse>non</reponse>
        <reponse>non en rouge</reponse>
        <reponse>Non avec une majuscule</reponse>
        <reponse>NON en majlock</reponse>
    </question>
</QCM>
