=== FC-Dijkstra/SiteFormation_DAW/back/data/evaluation/questions/questions.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT QCM (meta, question+)>
<!ELEMENT meta (id, cours, difficulte)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT cours (#PCDATA)>
<!ELEMENT difficulte (#PCDATA)>
<!ELEMENT question (id, enonce, reponse+)>
<!ELEMENT enonce (#PCDATA)>
<!ELEMENT reponse (id, value)>
<!ELEMENT value (#PCDATA)>

=== FC-Dijkstra/SiteFormation_DAW/back/XML/questions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE QCM SYSTEM "questions.dtd">
<QCM>
    <meta>
        <id>1</id>
        <cours>Développement Web</cours>
        <difficulte>Facile</difficulte>
    </meta>
    <question>
        <id>1</id>
        <enonce>Quel langage utilise t'on pour gérer une BD ?</enonce>
        <reponse>
            <id>a</id>
            <value>SQL</value>
        </reponse>
        <reponse>
            <id>b</id>
            <value>HTML</value>
        </reponse>
        <reponse>
            <id>c</id>
            <value>C++</value>
        </reponse>
    </question>
</QCM>

=== FC-Dijkstra/SiteFormation_DAW/back/data/evaluation/questions/questions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE QCM SYSTEM "questions.dtd">
<QCM>
    <meta>
        <id>1</id>
        <cours>Développement Web</cours>
        <difficulte>Facile</difficulte>
    </meta>
    <question>
        <id>1</id>
        <enonce>Quel langage utilise t'on pour gérer une BD ?</enonce>
        <reponse>
            <id>a</id>
            <value>SQL</value>
        </reponse>
        <reponse>
            <id>b</id>
            <value>HTML</value>
        </reponse>
        <reponse>
            <id>c</id>
            <value>C++</value>
        </reponse>
    </question>
    <question>
        <id>2</id>
        <enonce>La question 2: </enonce>
        <reponse>
            <id>a</id>
            <value>Réponse a</value>
        </reponse>
        <reponse>
            <id>b</id>
            <value>Réponse a</value>
        </reponse>
        <reponse>
            <id>c</id>
            <value>Réponse a</value>
        </reponse>
        <reponse>
            <id>d</id>
            <value>Réponse a</value>
        </reponse>
    </question>
</QCM>
